
export default [
  {
    title: `Titulo de la Entrada`,
    entry: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non erat in mi luctus blandit ac eget purus. Aliquam tincidunt, nisi vitae dapibus euismod, nulla eros iaculis tellus, vitae condimentum nunc enim eu felis. In laoreet nulla quis viverra imperdiet. Duis fringilla eu odio sit amet pharetra. Mauris eros nunc, efficitur eget dolor sit amet, imperdiet tempus dui. Nullam semper urna eu purus faucibus, et eleifend justo pellentesque. Morbi felis elit, efficitur a diam nec, accumsan facilisis urna. Nam at magna sed purus fringilla ullamcorper at nec metus. Phasellus elementum mauris arcu, ac aliquam justo molestie sit amet. Aenean quis efficitur diam. Integer aliquet lobortis nunc non eleifend. In hac habitasse platea dictumst. Vestibulum eu enim aliquet, hendrerit eros eget, tempor orci. Maecenas condimentum lacus nec euismod posuere. Integer sit amet gravida ipsum.

Donec ultricies maximus tortor. Suspendisse vehicula risus a metus varius, ut feugiat nulla faucibus. Aenean facilisis elit odio, nec sollicitudin eros elementum sit amet. Proin posuere sem arcu, nec consectetur risus facilisis non. Nam non felis hendrerit, euismod nulla at, malesuada augue. Phasellus pharetra aliquet velit ac finibus. Curabitur diam leo, eleifend eu vestibulum vitae, consectetur sit amet nulla. Cras a feugiat nulla. Fusce accumsan sapien at dui elementum gravida. Maecenas euismod mauris sit amet nisi varius, at auctor quam aliquet. Aliquam vel dignissim eros. Aliquam bibendum orci ante, sit amet ultrices ipsum hendrerit eu. Donec ac arcu quis est bibendum placerat at in sapien. Sed et justo rutrum, dapibus dui sed, interdum leo. Cras libero libero, imperdiet vel maximus sodales, faucibus ut ipsum. Proin nec consequat nulla.

In hac habitasse platea dictumst. Vestibulum sed quam non libero vehicula mattis. Cras pretium eros metus, at porta orci tincidunt vitae. Nullam ut venenatis nisl, ut finibus dui. Fusce congue neque eu justo iaculis posuere. Praesent lacinia nibh et quam congue posuere. In ac dui vitae felis convallis ultrices ut nec est. Aliquam pulvinar lorem magna, a aliquam augue molestie non. Cras pharetra tincidunt dolor, eget gravida dui eleifend et.

In tempus, tellus nec interdum suscipit, tellus nisi interdum felis, ut tempor dolor neque ac elit. Nam varius dolor vitae consectetur pretium. Duis gravida augue felis, a posuere risus fermentum vel. Morbi a porta arcu. Vivamus aliquet dictum mattis. Aliquam laoreet tellus at neque dignissim, ut imperdiet justo semper. Etiam eu justo vulputate, eleifend est id, tincidunt felis.

Pellentesque ultricies erat non ex gravida sollicitudin. In sed eros et orci tristique placerat suscipit quis tortor. Ut tristique rhoncus quam, sed lobortis mauris varius sed. Sed bibendum ornare velit, sit amet lobortis orci sodales ut. Maecenas odio est, congue sit amet felis ac, tincidunt ultricies libero. Suspendisse aliquam metus mi, sed viverra libero vestibulum sit amet. Proin ornare, libero a suscipit volutpat, turpis nisl tristique lectus, eu feugiat urna sem at mauris.`,
category: 'Health'
  }
]